name: test the chio
on: push
jobs:
  smoketest:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install test dependencies
        run: |
          pip install pytest pytest-dependency asteval ipython
          apt install socat

      - name: Run tests against dojo
        run: |
          pytest -vrpP ./test.py
